//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_generacii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Акт наруш правил.
    /// </summary>
    // *** Start programmer edit section *** (АктНарушПравил CustomAttributes)

    // *** End programmer edit section *** (АктНарушПравил CustomAttributes)
    [AutoAltered()]
    [Caption("Акт наруш правил")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АктНарушПравилE", new string[] {
            "Дата as \'Дата\'",
            "НомерДок as \'Номер док\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТЧСоставУщерба as \'Т ч состав ущерба\'",
            "ТЧСоставУщерба.СуммаУщерба as \'Сумма ущерба\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "Клиенты.ФИО",
            "Персонал.ФИО",
            "ТЧСоставУщерба.СуммаУщерба"})]
    [MasterViewDefineAttribute("АктНарушПравилE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("АктНарушПравилE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("АктНарушПравилE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("АктНарушПравилE", "ТЧСоставУщерба", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "СуммаУщерба")]
    [View("АктНарушПравилL", new string[] {
            "Дата as \'Дата\'",
            "НомерДок as \'Номер док\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты.ФИО as \'ФИО\'",
            "Персонал.ФИО as \'ФИО\'",
            "ТЧСоставУщерба.СуммаУщерба as \'Сумма ущерба\'"})]
    public class АктНарушПравил : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерДок;
        
        private IIS.Dlya_generacii.Организация fОрганизация;
        
        private IIS.Dlya_generacii.Клиенты fКлиенты;
        
        private IIS.Dlya_generacii.Персонал fПерсонал;
        
        private IIS.Dlya_generacii.ТЧСоставУщерба fТЧСоставУщерба;
        
        // *** Start programmer edit section *** (АктНарушПравил CustomMembers)

        // *** End programmer edit section *** (АктНарушПравил CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.Дата CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.Дата Get start)

                // *** End programmer edit section *** (АктНарушПравил.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (АктНарушПравил.Дата Get end)

                // *** End programmer edit section *** (АктНарушПравил.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.Дата Set start)

                // *** End programmer edit section *** (АктНарушПравил.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (АктНарушПравил.Дата Set end)

                // *** End programmer edit section *** (АктНарушПравил.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.НомерДок CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.НомерДок Get start)

                // *** End programmer edit section *** (АктНарушПравил.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (АктНарушПравил.НомерДок Get end)

                // *** End programmer edit section *** (АктНарушПравил.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.НомерДок Set start)

                // *** End programmer edit section *** (АктНарушПравил.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (АктНарушПравил.НомерДок Set end)

                // *** End programmer edit section *** (АктНарушПравил.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// Акт наруш правил.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.Клиенты CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.Клиенты Get start)

                // *** End programmer edit section *** (АктНарушПравил.Клиенты Get start)
                IIS.Dlya_generacii.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (АктНарушПравил.Клиенты Get end)

                // *** End programmer edit section *** (АктНарушПравил.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.Клиенты Set start)

                // *** End programmer edit section *** (АктНарушПравил.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (АктНарушПравил.Клиенты Set end)

                // *** End programmer edit section *** (АктНарушПравил.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Акт наруш правил.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.Организация CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.Организация Get start)

                // *** End programmer edit section *** (АктНарушПравил.Организация Get start)
                IIS.Dlya_generacii.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (АктНарушПравил.Организация Get end)

                // *** End programmer edit section *** (АктНарушПравил.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.Организация Set start)

                // *** End programmer edit section *** (АктНарушПравил.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (АктНарушПравил.Организация Set end)

                // *** End programmer edit section *** (АктНарушПравил.Организация Set end)
            }
        }
        
        /// <summary>
        /// Акт наруш правил.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.Персонал CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.Персонал Get start)

                // *** End programmer edit section *** (АктНарушПравил.Персонал Get start)
                IIS.Dlya_generacii.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (АктНарушПравил.Персонал Get end)

                // *** End programmer edit section *** (АктНарушПравил.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.Персонал Set start)

                // *** End programmer edit section *** (АктНарушПравил.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (АктНарушПравил.Персонал Set end)

                // *** End programmer edit section *** (АктНарушПравил.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Акт наруш правил.
        /// </summary>
        // *** Start programmer edit section *** (АктНарушПравил.ТЧСоставУщерба CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.ТЧСоставУщерба CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧСоставУщерба"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.ТЧСоставУщерба ТЧСоставУщерба
        {
            get
            {
                // *** Start programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Get start)

                // *** End programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Get start)
                IIS.Dlya_generacii.ТЧСоставУщерба result = this.fТЧСоставУщерба;
                // *** Start programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Get end)

                // *** End programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Set start)

                // *** End programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Set start)
                this.fТЧСоставУщерба = value;
                // *** Start programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Set end)

                // *** End programmer edit section *** (АктНарушПравил.ТЧСоставУщерба Set end)
            }
        }
        
        // *** Start programmer edit section *** (АктНарушПравил.Отправить CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (АктНарушПравил.Отправить method implementation)

            return;
            // *** End programmer edit section *** (АктНарушПравил.Отправить method implementation)
        }
        
        // *** Start programmer edit section *** (АктНарушПравил.Распечатать CustomAttributes)

        // *** End programmer edit section *** (АктНарушПравил.Распечатать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Распечатать()
        {
            // *** Start programmer edit section *** (АктНарушПравил.Распечатать method implementation)

            return;
            // *** End programmer edit section *** (АктНарушПравил.Распечатать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АктНарушПравилE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктНарушПравилE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктНарушПравилE", typeof(IIS.Dlya_generacii.АктНарушПравил));
                }
            }
            
            /// <summary>
            /// "АктНарушПравилL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктНарушПравилL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктНарушПравилL", typeof(IIS.Dlya_generacii.АктНарушПравил));
                }
            }
        }
    }
}
