//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_generacii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доп услуги.
    /// </summary>
    // *** Start programmer edit section *** (ДопУслуги CustomAttributes)

    // *** End programmer edit section *** (ДопУслуги CustomAttributes)
    [AutoAltered()]
    [Caption("Доп услуги")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДопУслугиE", new string[] {
            "Услуга as \'Услуга\'",
            "ОписУслуги as \'Опис услуги\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ДопУслугиL", new string[] {
            "Услуга as \'Услуга\'",
            "ОписУслуги as \'Опис услуги\'",
            "Стоимость as \'Стоимость\'"})]
    public class ДопУслуги : ICSSoft.STORMNET.DataObject
    {
        
        private string fУслуга;
        
        private string fОписУслуги;
        
        private double fСтоимость;
        
        // *** Start programmer edit section *** (ДопУслуги CustomMembers)

        // *** End programmer edit section *** (ДопУслуги CustomMembers)

        
        /// <summary>
        /// ОписУслуги.
        /// </summary>
        // *** Start programmer edit section *** (ДопУслуги.ОписУслуги CustomAttributes)

        // *** End programmer edit section *** (ДопУслуги.ОписУслуги CustomAttributes)
        [StrLen(255)]
        public virtual string ОписУслуги
        {
            get
            {
                // *** Start programmer edit section *** (ДопУслуги.ОписУслуги Get start)

                // *** End programmer edit section *** (ДопУслуги.ОписУслуги Get start)
                string result = this.fОписУслуги;
                // *** Start programmer edit section *** (ДопУслуги.ОписУслуги Get end)

                // *** End programmer edit section *** (ДопУслуги.ОписУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопУслуги.ОписУслуги Set start)

                // *** End programmer edit section *** (ДопУслуги.ОписУслуги Set start)
                this.fОписУслуги = value;
                // *** Start programmer edit section *** (ДопУслуги.ОписУслуги Set end)

                // *** End programmer edit section *** (ДопУслуги.ОписУслуги Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ДопУслуги.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ДопУслуги.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ДопУслуги.Стоимость Get start)

                // *** End programmer edit section *** (ДопУслуги.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (ДопУслуги.Стоимость Get end)

                // *** End programmer edit section *** (ДопУслуги.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопУслуги.Стоимость Set start)

                // *** End programmer edit section *** (ДопУслуги.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ДопУслуги.Стоимость Set end)

                // *** End programmer edit section *** (ДопУслуги.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (ДопУслуги.Услуга CustomAttributes)

        // *** End programmer edit section *** (ДопУслуги.Услуга CustomAttributes)
        [StrLen(255)]
        public virtual string Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ДопУслуги.Услуга Get start)

                // *** End programmer edit section *** (ДопУслуги.Услуга Get start)
                string result = this.fУслуга;
                // *** Start programmer edit section *** (ДопУслуги.Услуга Get end)

                // *** End programmer edit section *** (ДопУслуги.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДопУслуги.Услуга Set start)

                // *** End programmer edit section *** (ДопУслуги.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ДопУслуги.Услуга Set end)

                // *** End programmer edit section *** (ДопУслуги.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДопУслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопУслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопУслугиE", typeof(IIS.Dlya_generacii.ДопУслуги));
                }
            }
            
            /// <summary>
            /// "ДопУслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопУслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопУслугиL", typeof(IIS.Dlya_generacii.ДопУслуги));
                }
            }
        }
    }
}
