//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_generacii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Жалоба клиента.
    /// </summary>
    // *** Start programmer edit section *** (ЖалобаКлиента CustomAttributes)

    // *** End programmer edit section *** (ЖалобаКлиента CustomAttributes)
    [AutoAltered()]
    [Caption("Жалоба клиента")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖалобаКлиентаE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО\'",
            "ТЧСоставЖалобы as \'Т ч состав жалобы\'",
            "ТЧСоставЖалобы.ОписаниеЖалобы as \'Описание жалобы\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Клиенты.ФИО",
            "ТЧСоставЖалобы.ОписаниеЖалобы",
            "Организация.Наименование"})]
    [MasterViewDefineAttribute("ЖалобаКлиентаE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ЖалобаКлиентаE", "ТЧСоставЖалобы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ОписаниеЖалобы")]
    [MasterViewDefineAttribute("ЖалобаКлиентаE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ЖалобаКлиентаL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Организация.Наименование as \'Наименование\'",
            "Клиенты.ФИО as \'ФИО\'",
            "Клиенты.Телефон as \'Телефон\'",
            "ТЧСоставЖалобы.ОписаниеЖалобы as \'Описание жалобы\'",
            "ТЧСоставЖалобы.ПринятыеМеры as \'Принятые меры\'",
            "ТЧСоставЖалобы.Персонал.Должности.Наименование as \'Ответственный\'",
            "ТЧСоставЖалобы.Персонал.ФИО as \'ФИО\'"})]
    public class ЖалобаКлиента : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Dlya_generacii.Клиенты fКлиенты;
        
        private IIS.Dlya_generacii.ТЧСоставЖалобы fТЧСоставЖалобы;
        
        private IIS.Dlya_generacii.Организация fОрганизация;
        
        // *** Start programmer edit section *** (ЖалобаКлиента CustomMembers)

        // *** End programmer edit section *** (ЖалобаКлиента CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЖалобаКлиента.Дата CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Дата Get start)

                // *** End programmer edit section *** (ЖалобаКлиента.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЖалобаКлиента.Дата Get end)

                // *** End programmer edit section *** (ЖалобаКлиента.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Дата Set start)

                // *** End programmer edit section *** (ЖалобаКлиента.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЖалобаКлиента.Дата Set end)

                // *** End programmer edit section *** (ЖалобаКлиента.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЖалобаКлиента.Номер CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Номер Get start)

                // *** End programmer edit section *** (ЖалобаКлиента.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЖалобаКлиента.Номер Get end)

                // *** End programmer edit section *** (ЖалобаКлиента.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Номер Set start)

                // *** End programmer edit section *** (ЖалобаКлиента.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЖалобаКлиента.Номер Set end)

                // *** End programmer edit section *** (ЖалобаКлиента.Номер Set end)
            }
        }
        
        /// <summary>
        /// Жалоба клиента.
        /// </summary>
        // *** Start programmer edit section *** (ЖалобаКлиента.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Клиенты Get start)

                // *** End programmer edit section *** (ЖалобаКлиента.Клиенты Get start)
                IIS.Dlya_generacii.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ЖалобаКлиента.Клиенты Get end)

                // *** End programmer edit section *** (ЖалобаКлиента.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Клиенты Set start)

                // *** End programmer edit section *** (ЖалобаКлиента.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ЖалобаКлиента.Клиенты Set end)

                // *** End programmer edit section *** (ЖалобаКлиента.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Жалоба клиента.
        /// </summary>
        // *** Start programmer edit section *** (ЖалобаКлиента.Организация CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Организация Get start)

                // *** End programmer edit section *** (ЖалобаКлиента.Организация Get start)
                IIS.Dlya_generacii.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ЖалобаКлиента.Организация Get end)

                // *** End programmer edit section *** (ЖалобаКлиента.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.Организация Set start)

                // *** End programmer edit section *** (ЖалобаКлиента.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ЖалобаКлиента.Организация Set end)

                // *** End programmer edit section *** (ЖалобаКлиента.Организация Set end)
            }
        }
        
        /// <summary>
        /// Жалоба клиента.
        /// </summary>
        // *** Start programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧСоставЖалобы"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.ТЧСоставЖалобы ТЧСоставЖалобы
        {
            get
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Get start)

                // *** End programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Get start)
                IIS.Dlya_generacii.ТЧСоставЖалобы result = this.fТЧСоставЖалобы;
                // *** Start programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Get end)

                // *** End programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Set start)

                // *** End programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Set start)
                this.fТЧСоставЖалобы = value;
                // *** Start programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Set end)

                // *** End programmer edit section *** (ЖалобаКлиента.ТЧСоставЖалобы Set end)
            }
        }
        
        // *** Start programmer edit section *** (ЖалобаКлиента.Отправить CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (ЖалобаКлиента.Отправить method implementation)

            return;
            // *** End programmer edit section *** (ЖалобаКлиента.Отправить method implementation)
        }
        
        // *** Start programmer edit section *** (ЖалобаКлиента.Распечатать CustomAttributes)

        // *** End programmer edit section *** (ЖалобаКлиента.Распечатать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Распечатать()
        {
            // *** Start programmer edit section *** (ЖалобаКлиента.Распечатать method implementation)

            return;
            // *** End programmer edit section *** (ЖалобаКлиента.Распечатать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖалобаКлиентаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖалобаКлиентаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖалобаКлиентаE", typeof(IIS.Dlya_generacii.ЖалобаКлиента));
                }
            }
            
            /// <summary>
            /// "ЖалобаКлиентаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖалобаКлиентаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖалобаКлиентаL", typeof(IIS.Dlya_generacii.ЖалобаКлиента));
                }
            }
        }
    }
}
