//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_generacii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч состав ущерба.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСоставУщерба CustomAttributes)

    // *** End programmer edit section *** (ТЧСоставУщерба CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч состав ущерба")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСоставУщербаE", new string[] {
            "СуммаУщерба as \'Сумма ущерба\'",
            "Количество as \'Количество\'",
            "ВидыУщерба as \'Виды ущерба\'",
            "ВидыУщерба.ВидУщерба as \'Вид ущерба\'"}, Hidden=new string[] {
            "ВидыУщерба.ВидУщерба"})]
    [MasterViewDefineAttribute("ТЧСоставУщербаE", "ВидыУщерба", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ВидУщерба")]
    [View("ТЧСоставУщербаL", new string[] {
            "СуммаУщерба as \'Сумма ущерба\'",
            "Количество as \'Количество\'",
            "ВидыУщерба.ВидУщерба as \'Вид ущерба\'"})]
    public class ТЧСоставУщерба : ICSSoft.STORMNET.DataObject
    {
        
        private double fСуммаУщерба;
        
        private int fКоличество;
        
        private IIS.Dlya_generacii.ВидыУщерба fВидыУщерба;
        
        // *** Start programmer edit section *** (ТЧСоставУщерба CustomMembers)

        // *** End programmer edit section *** (ТЧСоставУщерба CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставУщерба.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставУщерба.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.Количество Get start)

                // *** End programmer edit section *** (ТЧСоставУщерба.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧСоставУщерба.Количество Get end)

                // *** End programmer edit section *** (ТЧСоставУщерба.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.Количество Set start)

                // *** End programmer edit section *** (ТЧСоставУщерба.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧСоставУщерба.Количество Set end)

                // *** End programmer edit section *** (ТЧСоставУщерба.Количество Set end)
            }
        }
        
        /// <summary>
        /// СуммаУщерба.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставУщерба.СуммаУщерба CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставУщерба.СуммаУщерба CustomAttributes)
        public virtual double СуммаУщерба
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Get start)

                // *** End programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Get start)
                double result = this.fСуммаУщерба;
                // *** Start programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Get end)

                // *** End programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Set start)

                // *** End programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Set start)
                this.fСуммаУщерба = value;
                // *** Start programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Set end)

                // *** End programmer edit section *** (ТЧСоставУщерба.СуммаУщерба Set end)
            }
        }
        
        /// <summary>
        /// Т ч состав ущерба.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставУщерба.ВидыУщерба CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставУщерба.ВидыУщерба CustomAttributes)
        [PropertyStorage(new string[] {
                "ВидыУщерба"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.ВидыУщерба ВидыУщерба
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Get start)

                // *** End programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Get start)
                IIS.Dlya_generacii.ВидыУщерба result = this.fВидыУщерба;
                // *** Start programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Get end)

                // *** End programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Set start)

                // *** End programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Set start)
                this.fВидыУщерба = value;
                // *** Start programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Set end)

                // *** End programmer edit section *** (ТЧСоставУщерба.ВидыУщерба Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСоставУщербаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставУщербаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставУщербаE", typeof(IIS.Dlya_generacii.ТЧСоставУщерба));
                }
            }
            
            /// <summary>
            /// "ТЧСоставУщербаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставУщербаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставУщербаL", typeof(IIS.Dlya_generacii.ТЧСоставУщерба));
                }
            }
        }
    }
}
