//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Dlya_generacii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч состав жалобы.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСоставЖалобы CustomAttributes)

    // *** End programmer edit section *** (ТЧСоставЖалобы CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч состав жалобы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСоставЖалобыE", new string[] {
            "ОписаниеЖалобы as \'Описание жалобы\'",
            "ПринятыеМеры as \'Принятые меры\'",
            "Персонал as \'Персонал\'",
            "Персонал.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Персонал.ФИО"})]
    [MasterViewDefineAttribute("ТЧСоставЖалобыE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ТЧСоставЖалобыL", new string[] {
            "ОписаниеЖалобы as \'Описание жалобы\'",
            "ПринятыеМеры as \'Принятые меры\'",
            "Персонал.ФИО as \'ФИО\'"})]
    public class ТЧСоставЖалобы : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписаниеЖалобы;
        
        private string fПринятыеМеры;
        
        private IIS.Dlya_generacii.Персонал fПерсонал;
        
        // *** Start programmer edit section *** (ТЧСоставЖалобы CustomMembers)

        // *** End programmer edit section *** (ТЧСоставЖалобы CustomMembers)

        
        /// <summary>
        /// ОписаниеЖалобы.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы CustomAttributes)
        [StrLen(255)]
        public virtual string ОписаниеЖалобы
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Get start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Get start)
                string result = this.fОписаниеЖалобы;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Get end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Set start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Set start)
                this.fОписаниеЖалобы = value;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Set end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ОписаниеЖалобы Set end)
            }
        }
        
        /// <summary>
        /// ПринятыеМеры.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры CustomAttributes)
        [StrLen(255)]
        public virtual string ПринятыеМеры
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Get start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Get start)
                string result = this.fПринятыеМеры;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Get end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Set start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Set start)
                this.fПринятыеМеры = value;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Set end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.ПринятыеМеры Set end)
            }
        }
        
        /// <summary>
        /// Т ч состав жалобы.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСоставЖалобы.Персонал CustomAttributes)

        // *** End programmer edit section *** (ТЧСоставЖалобы.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.Dlya_generacii.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.Персонал Get start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.Персонал Get start)
                IIS.Dlya_generacii.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.Персонал Get end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСоставЖалобы.Персонал Set start)

                // *** End programmer edit section *** (ТЧСоставЖалобы.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (ТЧСоставЖалобы.Персонал Set end)

                // *** End programmer edit section *** (ТЧСоставЖалобы.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСоставЖалобыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставЖалобыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставЖалобыE", typeof(IIS.Dlya_generacii.ТЧСоставЖалобы));
                }
            }
            
            /// <summary>
            /// "ТЧСоставЖалобыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСоставЖалобыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСоставЖалобыL", typeof(IIS.Dlya_generacii.ТЧСоставЖалобы));
                }
            }
        }
    }
}
